/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BharatVote {
  export type CandidateStruct = {
    id: BigNumberish;
    name: string;
    isActive: boolean;
  };

  export type CandidateStructOutput = [
    id: bigint,
    name: string,
    isActive: boolean
  ] & { id: bigint; name: string; isActive: boolean };
}

export interface BharatVoteInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addCandidate"
      | "admin"
      | "candidateCount"
      | "candidates"
      | "clearAllCandidates"
      | "commitVote"
      | "commits"
      | "emergencyReset"
      | "finishElection"
      | "getCandidates"
      | "getTally"
      | "getVoterStatus"
      | "getVotes"
      | "hasCommitted"
      | "hasRevealed"
      | "initialize"
      | "merkleRoot"
      | "name"
      | "phase"
      | "removeCandidate"
      | "resetElection"
      | "revealVote"
      | "setMerkleRoot"
      | "startReveal"
      | "tally"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AllCandidatesCleared"
      | "CandidateAdded"
      | "CandidateRemoved"
      | "ElectionReset"
      | "Initialized"
      | "PhaseChanged"
      | "TallyFinalized"
      | "VoteCommitted"
      | "VoteRevealed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addCandidate",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "candidateCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "candidates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "clearAllCandidates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "commitVote",
    values: [BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "commits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyReset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finishElection",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCandidates",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getTally", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getVoterStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasCommitted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRevealed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "merkleRoot",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "phase", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeCandidate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resetElection",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealVote",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMerkleRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startReveal",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tally", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "addCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "candidateCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "candidates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "clearAllCandidates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "commitVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "commits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyReset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finishElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCandidates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTally", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVoterStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVotes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasCommitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasRevealed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "merkleRoot", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "phase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revealVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tally", data: BytesLike): Result;
}

export namespace AllCandidatesClearedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CandidateAddedEvent {
  export type InputTuple = [id: BigNumberish, name: string];
  export type OutputTuple = [id: bigint, name: string];
  export interface OutputObject {
    id: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CandidateRemovedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ElectionResetEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PhaseChangedEvent {
  export type InputTuple = [newPhase: BigNumberish];
  export type OutputTuple = [newPhase: bigint];
  export interface OutputObject {
    newPhase: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TallyFinalizedEvent {
  export type InputTuple = [finalTally: BigNumberish[]];
  export type OutputTuple = [finalTally: bigint[]];
  export interface OutputObject {
    finalTally: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCommittedEvent {
  export type InputTuple = [voter: AddressLike, commit: BytesLike];
  export type OutputTuple = [voter: string, commit: string];
  export interface OutputObject {
    voter: string;
    commit: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteRevealedEvent {
  export type InputTuple = [voter: AddressLike, choice: BigNumberish];
  export type OutputTuple = [voter: string, choice: bigint];
  export interface OutputObject {
    voter: string;
    choice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BharatVote extends BaseContract {
  connect(runner?: ContractRunner | null): BharatVote;
  waitForDeployment(): Promise<this>;

  interface: BharatVoteInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addCandidate: TypedContractMethod<[_name: string], [void], "nonpayable">;

  admin: TypedContractMethod<[], [string], "view">;

  candidateCount: TypedContractMethod<[], [bigint], "view">;

  candidates: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean] & {
        id: bigint;
        name: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  clearAllCandidates: TypedContractMethod<[], [void], "nonpayable">;

  commitVote: TypedContractMethod<
    [_commit: BytesLike, _proof: BytesLike[]],
    [void],
    "nonpayable"
  >;

  commits: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  emergencyReset: TypedContractMethod<[], [void], "nonpayable">;

  finishElection: TypedContractMethod<[], [void], "nonpayable">;

  getCandidates: TypedContractMethod<
    [],
    [BharatVote.CandidateStructOutput[]],
    "view"
  >;

  getTally: TypedContractMethod<[], [bigint[]], "view">;

  getVoterStatus: TypedContractMethod<
    [_voter: AddressLike],
    [[boolean, boolean] & { committed: boolean; revealed: boolean }],
    "view"
  >;

  getVotes: TypedContractMethod<[_id: BigNumberish], [bigint], "view">;

  hasCommitted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  hasRevealed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  initialize: TypedContractMethod<
    [_name: string, _admin: AddressLike],
    [void],
    "nonpayable"
  >;

  merkleRoot: TypedContractMethod<[], [string], "view">;

  name: TypedContractMethod<[], [string], "view">;

  phase: TypedContractMethod<[], [bigint], "view">;

  removeCandidate: TypedContractMethod<
    [_id: BigNumberish],
    [void],
    "nonpayable"
  >;

  resetElection: TypedContractMethod<[], [void], "nonpayable">;

  revealVote: TypedContractMethod<
    [_choice: BigNumberish, _salt: BytesLike],
    [void],
    "nonpayable"
  >;

  setMerkleRoot: TypedContractMethod<[_root: BytesLike], [void], "nonpayable">;

  startReveal: TypedContractMethod<[], [void], "nonpayable">;

  tally: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCandidate"
  ): TypedContractMethod<[_name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "candidateCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "candidates"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean] & {
        id: bigint;
        name: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "clearAllCandidates"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "commitVote"
  ): TypedContractMethod<
    [_commit: BytesLike, _proof: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commits"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "emergencyReset"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finishElection"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCandidates"
  ): TypedContractMethod<[], [BharatVote.CandidateStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getTally"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getVoterStatus"
  ): TypedContractMethod<
    [_voter: AddressLike],
    [[boolean, boolean] & { committed: boolean; revealed: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVotes"
  ): TypedContractMethod<[_id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasCommitted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasRevealed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_name: string, _admin: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "merkleRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "phase"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeCandidate"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resetElection"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revealVote"
  ): TypedContractMethod<
    [_choice: BigNumberish, _salt: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMerkleRoot"
  ): TypedContractMethod<[_root: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startReveal"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tally"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getEvent(
    key: "AllCandidatesCleared"
  ): TypedContractEvent<
    AllCandidatesClearedEvent.InputTuple,
    AllCandidatesClearedEvent.OutputTuple,
    AllCandidatesClearedEvent.OutputObject
  >;
  getEvent(
    key: "CandidateAdded"
  ): TypedContractEvent<
    CandidateAddedEvent.InputTuple,
    CandidateAddedEvent.OutputTuple,
    CandidateAddedEvent.OutputObject
  >;
  getEvent(
    key: "CandidateRemoved"
  ): TypedContractEvent<
    CandidateRemovedEvent.InputTuple,
    CandidateRemovedEvent.OutputTuple,
    CandidateRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ElectionReset"
  ): TypedContractEvent<
    ElectionResetEvent.InputTuple,
    ElectionResetEvent.OutputTuple,
    ElectionResetEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "PhaseChanged"
  ): TypedContractEvent<
    PhaseChangedEvent.InputTuple,
    PhaseChangedEvent.OutputTuple,
    PhaseChangedEvent.OutputObject
  >;
  getEvent(
    key: "TallyFinalized"
  ): TypedContractEvent<
    TallyFinalizedEvent.InputTuple,
    TallyFinalizedEvent.OutputTuple,
    TallyFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCommitted"
  ): TypedContractEvent<
    VoteCommittedEvent.InputTuple,
    VoteCommittedEvent.OutputTuple,
    VoteCommittedEvent.OutputObject
  >;
  getEvent(
    key: "VoteRevealed"
  ): TypedContractEvent<
    VoteRevealedEvent.InputTuple,
    VoteRevealedEvent.OutputTuple,
    VoteRevealedEvent.OutputObject
  >;

  filters: {
    "AllCandidatesCleared()": TypedContractEvent<
      AllCandidatesClearedEvent.InputTuple,
      AllCandidatesClearedEvent.OutputTuple,
      AllCandidatesClearedEvent.OutputObject
    >;
    AllCandidatesCleared: TypedContractEvent<
      AllCandidatesClearedEvent.InputTuple,
      AllCandidatesClearedEvent.OutputTuple,
      AllCandidatesClearedEvent.OutputObject
    >;

    "CandidateAdded(uint256,string)": TypedContractEvent<
      CandidateAddedEvent.InputTuple,
      CandidateAddedEvent.OutputTuple,
      CandidateAddedEvent.OutputObject
    >;
    CandidateAdded: TypedContractEvent<
      CandidateAddedEvent.InputTuple,
      CandidateAddedEvent.OutputTuple,
      CandidateAddedEvent.OutputObject
    >;

    "CandidateRemoved(uint256)": TypedContractEvent<
      CandidateRemovedEvent.InputTuple,
      CandidateRemovedEvent.OutputTuple,
      CandidateRemovedEvent.OutputObject
    >;
    CandidateRemoved: TypedContractEvent<
      CandidateRemovedEvent.InputTuple,
      CandidateRemovedEvent.OutputTuple,
      CandidateRemovedEvent.OutputObject
    >;

    "ElectionReset()": TypedContractEvent<
      ElectionResetEvent.InputTuple,
      ElectionResetEvent.OutputTuple,
      ElectionResetEvent.OutputObject
    >;
    ElectionReset: TypedContractEvent<
      ElectionResetEvent.InputTuple,
      ElectionResetEvent.OutputTuple,
      ElectionResetEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "PhaseChanged(uint8)": TypedContractEvent<
      PhaseChangedEvent.InputTuple,
      PhaseChangedEvent.OutputTuple,
      PhaseChangedEvent.OutputObject
    >;
    PhaseChanged: TypedContractEvent<
      PhaseChangedEvent.InputTuple,
      PhaseChangedEvent.OutputTuple,
      PhaseChangedEvent.OutputObject
    >;

    "TallyFinalized(uint256[])": TypedContractEvent<
      TallyFinalizedEvent.InputTuple,
      TallyFinalizedEvent.OutputTuple,
      TallyFinalizedEvent.OutputObject
    >;
    TallyFinalized: TypedContractEvent<
      TallyFinalizedEvent.InputTuple,
      TallyFinalizedEvent.OutputTuple,
      TallyFinalizedEvent.OutputObject
    >;

    "VoteCommitted(address,bytes32)": TypedContractEvent<
      VoteCommittedEvent.InputTuple,
      VoteCommittedEvent.OutputTuple,
      VoteCommittedEvent.OutputObject
    >;
    VoteCommitted: TypedContractEvent<
      VoteCommittedEvent.InputTuple,
      VoteCommittedEvent.OutputTuple,
      VoteCommittedEvent.OutputObject
    >;

    "VoteRevealed(address,uint256)": TypedContractEvent<
      VoteRevealedEvent.InputTuple,
      VoteRevealedEvent.OutputTuple,
      VoteRevealedEvent.OutputObject
    >;
    VoteRevealed: TypedContractEvent<
      VoteRevealedEvent.InputTuple,
      VoteRevealedEvent.OutputTuple,
      VoteRevealedEvent.OutputObject
    >;
  };
}
