/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bharatVoteSol from "./BharatVote.sol";
export type { bharatVoteSol };
import type * as electionFactorySol from "./ElectionFactory.sol";
export type { electionFactorySol };
