/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as electionFactorySol from "./ElectionFactory.sol";
export type { electionFactorySol };
export type { BharatVote } from "./BharatVote";
