/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BharatVoteWithIPFS {
  export type ElectionDataStruct = {
    kycDataIPFS: string;
    voterListIPFS: string;
    resultsIPFS: string;
    auditTrailIPFS: string;
    timestamp: BigNumberish;
    isArchived: boolean;
  };

  export type ElectionDataStructOutput = [
    kycDataIPFS: string,
    voterListIPFS: string,
    resultsIPFS: string,
    auditTrailIPFS: string,
    timestamp: bigint,
    isArchived: boolean
  ] & {
    kycDataIPFS: string;
    voterListIPFS: string;
    resultsIPFS: string;
    auditTrailIPFS: string;
    timestamp: bigint;
    isArchived: boolean;
  };

  export type CandidateStruct = {
    id: BigNumberish;
    name: string;
    isActive: boolean;
    ipfsMetadata: string;
  };

  export type CandidateStructOutput = [
    id: bigint,
    name: string,
    isActive: boolean,
    ipfsMetadata: string
  ] & { id: bigint; name: string; isActive: boolean; ipfsMetadata: string };
}

export interface BharatVoteWithIPFSInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addCandidate"
      | "admin"
      | "archiveResults"
      | "archivedElections"
      | "candidateCount"
      | "candidates"
      | "clearAllCandidates"
      | "commitVote"
      | "commits"
      | "currentElection"
      | "emergencyReset"
      | "finishElection"
      | "getArchivedElection"
      | "getArchivedElectionsCount"
      | "getCandidates"
      | "getCurrentElectionData"
      | "getTally"
      | "getVoterProofIPFS"
      | "getVoterStatus"
      | "getVotes"
      | "hasCommitted"
      | "hasRevealed"
      | "merkleRoot"
      | "phase"
      | "removeCandidate"
      | "resetElection"
      | "revealVote"
      | "setAuditTrailIPFS"
      | "setKYCDataIPFS"
      | "setMerkleRoot"
      | "setVoterListIPFS"
      | "setVoterProofIPFS"
      | "startReveal"
      | "tally"
      | "voterProofIPFS"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AllCandidatesCleared"
      | "AuditTrailUpdated"
      | "CandidateAdded"
      | "CandidateRemoved"
      | "ElectionArchived"
      | "ElectionReset"
      | "KYCDataStored"
      | "PhaseChanged"
      | "ResultsArchived"
      | "TallyFinalized"
      | "VoteCommitted"
      | "VoteRevealed"
      | "VoterListStored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addCandidate",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "archiveResults",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "archivedElections",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "candidateCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "candidates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "clearAllCandidates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "commitVote",
    values: [BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "commits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentElection",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyReset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finishElection",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getArchivedElection",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getArchivedElectionsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCandidates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentElectionData",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getTally", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getVoterProofIPFS",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoterStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasCommitted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRevealed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "merkleRoot",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "phase", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeCandidate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resetElection",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealVote",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuditTrailIPFS",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setKYCDataIPFS",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMerkleRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVoterListIPFS",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setVoterProofIPFS",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "startReveal",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tally", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "voterProofIPFS",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "archiveResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "archivedElections",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "candidateCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "candidates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "clearAllCandidates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "commitVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "commits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyReset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finishElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArchivedElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getArchivedElectionsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCandidates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentElectionData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTally", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVoterProofIPFS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoterStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVotes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasCommitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasRevealed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "merkleRoot", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "phase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetElection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revealVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuditTrailIPFS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKYCDataIPFS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVoterListIPFS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVoterProofIPFS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tally", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voterProofIPFS",
    data: BytesLike
  ): Result;
}

export namespace AllCandidatesClearedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuditTrailUpdatedEvent {
  export type InputTuple = [ipfsHash: string, timestamp: BigNumberish];
  export type OutputTuple = [ipfsHash: string, timestamp: bigint];
  export interface OutputObject {
    ipfsHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CandidateAddedEvent {
  export type InputTuple = [id: BigNumberish, name: string, ipfsHash: string];
  export type OutputTuple = [id: bigint, name: string, ipfsHash: string];
  export interface OutputObject {
    id: bigint;
    name: string;
    ipfsHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CandidateRemovedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ElectionArchivedEvent {
  export type InputTuple = [electionId: BigNumberish, resultsIPFS: string];
  export type OutputTuple = [electionId: bigint, resultsIPFS: string];
  export interface OutputObject {
    electionId: bigint;
    resultsIPFS: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ElectionResetEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCDataStoredEvent {
  export type InputTuple = [ipfsHash: string, timestamp: BigNumberish];
  export type OutputTuple = [ipfsHash: string, timestamp: bigint];
  export interface OutputObject {
    ipfsHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PhaseChangedEvent {
  export type InputTuple = [newPhase: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [newPhase: bigint, timestamp: bigint];
  export interface OutputObject {
    newPhase: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultsArchivedEvent {
  export type InputTuple = [ipfsHash: string, timestamp: BigNumberish];
  export type OutputTuple = [ipfsHash: string, timestamp: bigint];
  export interface OutputObject {
    ipfsHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TallyFinalizedEvent {
  export type InputTuple = [finalTally: BigNumberish[], resultsIPFS: string];
  export type OutputTuple = [finalTally: bigint[], resultsIPFS: string];
  export interface OutputObject {
    finalTally: bigint[];
    resultsIPFS: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCommittedEvent {
  export type InputTuple = [
    voter: AddressLike,
    commit: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [voter: string, commit: string, timestamp: bigint];
  export interface OutputObject {
    voter: string;
    commit: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteRevealedEvent {
  export type InputTuple = [
    voter: AddressLike,
    choice: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [voter: string, choice: bigint, timestamp: bigint];
  export interface OutputObject {
    voter: string;
    choice: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoterListStoredEvent {
  export type InputTuple = [ipfsHash: string, timestamp: BigNumberish];
  export type OutputTuple = [ipfsHash: string, timestamp: bigint];
  export interface OutputObject {
    ipfsHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BharatVoteWithIPFS extends BaseContract {
  connect(runner?: ContractRunner | null): BharatVoteWithIPFS;
  waitForDeployment(): Promise<this>;

  interface: BharatVoteWithIPFSInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addCandidate: TypedContractMethod<
    [_name: string, _ipfsMetadata: string],
    [void],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  archiveResults: TypedContractMethod<
    [_ipfsHash: string],
    [void],
    "nonpayable"
  >;

  archivedElections: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, boolean] & {
        kycDataIPFS: string;
        voterListIPFS: string;
        resultsIPFS: string;
        auditTrailIPFS: string;
        timestamp: bigint;
        isArchived: boolean;
      }
    ],
    "view"
  >;

  candidateCount: TypedContractMethod<[], [bigint], "view">;

  candidates: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean, string] & {
        id: bigint;
        name: string;
        isActive: boolean;
        ipfsMetadata: string;
      }
    ],
    "view"
  >;

  clearAllCandidates: TypedContractMethod<[], [void], "nonpayable">;

  commitVote: TypedContractMethod<
    [_commit: BytesLike, _proof: BytesLike[]],
    [void],
    "nonpayable"
  >;

  commits: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  currentElection: TypedContractMethod<
    [],
    [
      [string, string, string, string, bigint, boolean] & {
        kycDataIPFS: string;
        voterListIPFS: string;
        resultsIPFS: string;
        auditTrailIPFS: string;
        timestamp: bigint;
        isArchived: boolean;
      }
    ],
    "view"
  >;

  emergencyReset: TypedContractMethod<[], [void], "nonpayable">;

  finishElection: TypedContractMethod<[], [void], "nonpayable">;

  getArchivedElection: TypedContractMethod<
    [_id: BigNumberish],
    [BharatVoteWithIPFS.ElectionDataStructOutput],
    "view"
  >;

  getArchivedElectionsCount: TypedContractMethod<[], [bigint], "view">;

  getCandidates: TypedContractMethod<
    [],
    [BharatVoteWithIPFS.CandidateStructOutput[]],
    "view"
  >;

  getCurrentElectionData: TypedContractMethod<
    [],
    [BharatVoteWithIPFS.ElectionDataStructOutput],
    "view"
  >;

  getTally: TypedContractMethod<[], [bigint[]], "view">;

  getVoterProofIPFS: TypedContractMethod<
    [_voter: AddressLike],
    [string],
    "view"
  >;

  getVoterStatus: TypedContractMethod<
    [_voter: AddressLike],
    [[boolean, boolean] & { committed: boolean; revealed: boolean }],
    "view"
  >;

  getVotes: TypedContractMethod<[_id: BigNumberish], [bigint], "view">;

  hasCommitted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  hasRevealed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  merkleRoot: TypedContractMethod<[], [string], "view">;

  phase: TypedContractMethod<[], [bigint], "view">;

  removeCandidate: TypedContractMethod<
    [_id: BigNumberish],
    [void],
    "nonpayable"
  >;

  resetElection: TypedContractMethod<[], [void], "nonpayable">;

  revealVote: TypedContractMethod<
    [_choice: BigNumberish, _salt: BytesLike],
    [void],
    "nonpayable"
  >;

  setAuditTrailIPFS: TypedContractMethod<
    [_ipfsHash: string],
    [void],
    "nonpayable"
  >;

  setKYCDataIPFS: TypedContractMethod<
    [_ipfsHash: string],
    [void],
    "nonpayable"
  >;

  setMerkleRoot: TypedContractMethod<[_root: BytesLike], [void], "nonpayable">;

  setVoterListIPFS: TypedContractMethod<
    [_ipfsHash: string],
    [void],
    "nonpayable"
  >;

  setVoterProofIPFS: TypedContractMethod<
    [_voter: AddressLike, _ipfsHash: string],
    [void],
    "nonpayable"
  >;

  startReveal: TypedContractMethod<[], [void], "nonpayable">;

  tally: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  voterProofIPFS: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCandidate"
  ): TypedContractMethod<
    [_name: string, _ipfsMetadata: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "archiveResults"
  ): TypedContractMethod<[_ipfsHash: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "archivedElections"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, boolean] & {
        kycDataIPFS: string;
        voterListIPFS: string;
        resultsIPFS: string;
        auditTrailIPFS: string;
        timestamp: bigint;
        isArchived: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "candidateCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "candidates"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean, string] & {
        id: bigint;
        name: string;
        isActive: boolean;
        ipfsMetadata: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "clearAllCandidates"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "commitVote"
  ): TypedContractMethod<
    [_commit: BytesLike, _proof: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commits"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "currentElection"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string, bigint, boolean] & {
        kycDataIPFS: string;
        voterListIPFS: string;
        resultsIPFS: string;
        auditTrailIPFS: string;
        timestamp: bigint;
        isArchived: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyReset"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finishElection"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getArchivedElection"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [BharatVoteWithIPFS.ElectionDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getArchivedElectionsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCandidates"
  ): TypedContractMethod<
    [],
    [BharatVoteWithIPFS.CandidateStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentElectionData"
  ): TypedContractMethod<
    [],
    [BharatVoteWithIPFS.ElectionDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTally"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getVoterProofIPFS"
  ): TypedContractMethod<[_voter: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getVoterStatus"
  ): TypedContractMethod<
    [_voter: AddressLike],
    [[boolean, boolean] & { committed: boolean; revealed: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVotes"
  ): TypedContractMethod<[_id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasCommitted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasRevealed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "merkleRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "phase"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeCandidate"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resetElection"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revealVote"
  ): TypedContractMethod<
    [_choice: BigNumberish, _salt: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAuditTrailIPFS"
  ): TypedContractMethod<[_ipfsHash: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setKYCDataIPFS"
  ): TypedContractMethod<[_ipfsHash: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMerkleRoot"
  ): TypedContractMethod<[_root: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVoterListIPFS"
  ): TypedContractMethod<[_ipfsHash: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVoterProofIPFS"
  ): TypedContractMethod<
    [_voter: AddressLike, _ipfsHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startReveal"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tally"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "voterProofIPFS"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "AllCandidatesCleared"
  ): TypedContractEvent<
    AllCandidatesClearedEvent.InputTuple,
    AllCandidatesClearedEvent.OutputTuple,
    AllCandidatesClearedEvent.OutputObject
  >;
  getEvent(
    key: "AuditTrailUpdated"
  ): TypedContractEvent<
    AuditTrailUpdatedEvent.InputTuple,
    AuditTrailUpdatedEvent.OutputTuple,
    AuditTrailUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CandidateAdded"
  ): TypedContractEvent<
    CandidateAddedEvent.InputTuple,
    CandidateAddedEvent.OutputTuple,
    CandidateAddedEvent.OutputObject
  >;
  getEvent(
    key: "CandidateRemoved"
  ): TypedContractEvent<
    CandidateRemovedEvent.InputTuple,
    CandidateRemovedEvent.OutputTuple,
    CandidateRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ElectionArchived"
  ): TypedContractEvent<
    ElectionArchivedEvent.InputTuple,
    ElectionArchivedEvent.OutputTuple,
    ElectionArchivedEvent.OutputObject
  >;
  getEvent(
    key: "ElectionReset"
  ): TypedContractEvent<
    ElectionResetEvent.InputTuple,
    ElectionResetEvent.OutputTuple,
    ElectionResetEvent.OutputObject
  >;
  getEvent(
    key: "KYCDataStored"
  ): TypedContractEvent<
    KYCDataStoredEvent.InputTuple,
    KYCDataStoredEvent.OutputTuple,
    KYCDataStoredEvent.OutputObject
  >;
  getEvent(
    key: "PhaseChanged"
  ): TypedContractEvent<
    PhaseChangedEvent.InputTuple,
    PhaseChangedEvent.OutputTuple,
    PhaseChangedEvent.OutputObject
  >;
  getEvent(
    key: "ResultsArchived"
  ): TypedContractEvent<
    ResultsArchivedEvent.InputTuple,
    ResultsArchivedEvent.OutputTuple,
    ResultsArchivedEvent.OutputObject
  >;
  getEvent(
    key: "TallyFinalized"
  ): TypedContractEvent<
    TallyFinalizedEvent.InputTuple,
    TallyFinalizedEvent.OutputTuple,
    TallyFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCommitted"
  ): TypedContractEvent<
    VoteCommittedEvent.InputTuple,
    VoteCommittedEvent.OutputTuple,
    VoteCommittedEvent.OutputObject
  >;
  getEvent(
    key: "VoteRevealed"
  ): TypedContractEvent<
    VoteRevealedEvent.InputTuple,
    VoteRevealedEvent.OutputTuple,
    VoteRevealedEvent.OutputObject
  >;
  getEvent(
    key: "VoterListStored"
  ): TypedContractEvent<
    VoterListStoredEvent.InputTuple,
    VoterListStoredEvent.OutputTuple,
    VoterListStoredEvent.OutputObject
  >;

  filters: {
    "AllCandidatesCleared()": TypedContractEvent<
      AllCandidatesClearedEvent.InputTuple,
      AllCandidatesClearedEvent.OutputTuple,
      AllCandidatesClearedEvent.OutputObject
    >;
    AllCandidatesCleared: TypedContractEvent<
      AllCandidatesClearedEvent.InputTuple,
      AllCandidatesClearedEvent.OutputTuple,
      AllCandidatesClearedEvent.OutputObject
    >;

    "AuditTrailUpdated(string,uint256)": TypedContractEvent<
      AuditTrailUpdatedEvent.InputTuple,
      AuditTrailUpdatedEvent.OutputTuple,
      AuditTrailUpdatedEvent.OutputObject
    >;
    AuditTrailUpdated: TypedContractEvent<
      AuditTrailUpdatedEvent.InputTuple,
      AuditTrailUpdatedEvent.OutputTuple,
      AuditTrailUpdatedEvent.OutputObject
    >;

    "CandidateAdded(uint256,string,string)": TypedContractEvent<
      CandidateAddedEvent.InputTuple,
      CandidateAddedEvent.OutputTuple,
      CandidateAddedEvent.OutputObject
    >;
    CandidateAdded: TypedContractEvent<
      CandidateAddedEvent.InputTuple,
      CandidateAddedEvent.OutputTuple,
      CandidateAddedEvent.OutputObject
    >;

    "CandidateRemoved(uint256)": TypedContractEvent<
      CandidateRemovedEvent.InputTuple,
      CandidateRemovedEvent.OutputTuple,
      CandidateRemovedEvent.OutputObject
    >;
    CandidateRemoved: TypedContractEvent<
      CandidateRemovedEvent.InputTuple,
      CandidateRemovedEvent.OutputTuple,
      CandidateRemovedEvent.OutputObject
    >;

    "ElectionArchived(uint256,string)": TypedContractEvent<
      ElectionArchivedEvent.InputTuple,
      ElectionArchivedEvent.OutputTuple,
      ElectionArchivedEvent.OutputObject
    >;
    ElectionArchived: TypedContractEvent<
      ElectionArchivedEvent.InputTuple,
      ElectionArchivedEvent.OutputTuple,
      ElectionArchivedEvent.OutputObject
    >;

    "ElectionReset()": TypedContractEvent<
      ElectionResetEvent.InputTuple,
      ElectionResetEvent.OutputTuple,
      ElectionResetEvent.OutputObject
    >;
    ElectionReset: TypedContractEvent<
      ElectionResetEvent.InputTuple,
      ElectionResetEvent.OutputTuple,
      ElectionResetEvent.OutputObject
    >;

    "KYCDataStored(string,uint256)": TypedContractEvent<
      KYCDataStoredEvent.InputTuple,
      KYCDataStoredEvent.OutputTuple,
      KYCDataStoredEvent.OutputObject
    >;
    KYCDataStored: TypedContractEvent<
      KYCDataStoredEvent.InputTuple,
      KYCDataStoredEvent.OutputTuple,
      KYCDataStoredEvent.OutputObject
    >;

    "PhaseChanged(uint8,uint256)": TypedContractEvent<
      PhaseChangedEvent.InputTuple,
      PhaseChangedEvent.OutputTuple,
      PhaseChangedEvent.OutputObject
    >;
    PhaseChanged: TypedContractEvent<
      PhaseChangedEvent.InputTuple,
      PhaseChangedEvent.OutputTuple,
      PhaseChangedEvent.OutputObject
    >;

    "ResultsArchived(string,uint256)": TypedContractEvent<
      ResultsArchivedEvent.InputTuple,
      ResultsArchivedEvent.OutputTuple,
      ResultsArchivedEvent.OutputObject
    >;
    ResultsArchived: TypedContractEvent<
      ResultsArchivedEvent.InputTuple,
      ResultsArchivedEvent.OutputTuple,
      ResultsArchivedEvent.OutputObject
    >;

    "TallyFinalized(uint256[],string)": TypedContractEvent<
      TallyFinalizedEvent.InputTuple,
      TallyFinalizedEvent.OutputTuple,
      TallyFinalizedEvent.OutputObject
    >;
    TallyFinalized: TypedContractEvent<
      TallyFinalizedEvent.InputTuple,
      TallyFinalizedEvent.OutputTuple,
      TallyFinalizedEvent.OutputObject
    >;

    "VoteCommitted(address,bytes32,uint256)": TypedContractEvent<
      VoteCommittedEvent.InputTuple,
      VoteCommittedEvent.OutputTuple,
      VoteCommittedEvent.OutputObject
    >;
    VoteCommitted: TypedContractEvent<
      VoteCommittedEvent.InputTuple,
      VoteCommittedEvent.OutputTuple,
      VoteCommittedEvent.OutputObject
    >;

    "VoteRevealed(address,uint256,uint256)": TypedContractEvent<
      VoteRevealedEvent.InputTuple,
      VoteRevealedEvent.OutputTuple,
      VoteRevealedEvent.OutputObject
    >;
    VoteRevealed: TypedContractEvent<
      VoteRevealedEvent.InputTuple,
      VoteRevealedEvent.OutputTuple,
      VoteRevealedEvent.OutputObject
    >;

    "VoterListStored(string,uint256)": TypedContractEvent<
      VoterListStoredEvent.InputTuple,
      VoterListStoredEvent.OutputTuple,
      VoterListStoredEvent.OutputObject
    >;
    VoterListStored: TypedContractEvent<
      VoterListStoredEvent.InputTuple,
      VoterListStoredEvent.OutputTuple,
      VoterListStoredEvent.OutputObject
    >;
  };
}
