/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBharatVote,
  IBharatVoteInterface,
} from "../../../contracts/ElectionFactory.sol/IBharatVote";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        internalType: "address",
        name: "_admin",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBharatVote__factory {
  static readonly abi = _abi;
  static createInterface(): IBharatVoteInterface {
    return new Interface(_abi) as IBharatVoteInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IBharatVote {
    return new Contract(address, _abi, runner) as unknown as IBharatVote;
  }
}
