/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as create2Sol from "./Create2.sol";
export type { create2Sol };
import type * as errorsSol from "./Errors.sol";
export type { errorsSol };
