/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bharatVoteSol from "./BharatVote.sol";
export type { bharatVoteSol };
import type * as bharatVoteWithIpfsSol from "./BharatVoteWithIPFS.sol";
export type { bharatVoteWithIpfsSol };
import type * as electionFactorySol from "./ElectionFactory.sol";
export type { electionFactorySol };
import type * as lockSol from "./Lock.sol";
export type { lockSol };
