/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bharatVoteSol from "./BharatVote.sol";
export type { bharatVoteSol };
import type * as bharatVoteWithIpfsSol from "./BharatVoteWithIPFS.sol";
export type { bharatVoteWithIpfsSol };
import type * as lockSol from "./Lock.sol";
export type { lockSol };
export * as factories from "./factories";
export type { Lock } from "./Lock.sol/Lock";
export { Lock__factory } from "./factories/Lock.sol/Lock__factory";
export type { BharatVoteWithIPFS } from "./BharatVoteWithIPFS.sol/BharatVoteWithIPFS";
export { BharatVoteWithIPFS__factory } from "./factories/BharatVoteWithIPFS.sol/BharatVoteWithIPFS__factory";
export type { BharatVote } from "./BharatVote.sol/BharatVote";
export { BharatVote__factory } from "./factories/BharatVote.sol/BharatVote__factory";
