/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as bharatVoteSol from "./BharatVote.sol";
export * as bharatVoteWithIpfsSol from "./BharatVoteWithIPFS.sol";
export * as electionFactorySol from "./ElectionFactory.sol";
export * as lockSol from "./Lock.sol";
