/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as electionFactorySol from "./ElectionFactory.sol";
export { BharatVote__factory } from "./BharatVote__factory";
