/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as clonesSol from "./Clones.sol";
export type { clonesSol };
import type * as utils from "./utils";
export type { utils };
