/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ElectionFactory__factory } from "./ElectionFactory__factory";
export { IBharatVote__factory } from "./IBharatVote__factory";
